# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/mholt/caddy"
  revision = "13f9c34d161693c1c0828fea3750d01c068174b6"

[[override]]
  name = "github.com/xenolf/lego"
  revision = "fad2257e11ae4ff31ed03739386873aa405dec2d"

[[override]]
  name = "github.com/russross/blackfriday"
  revision = "067529f716f4c3f5e37c8c95ddd59df1007290ae"

[[override]]
  name = "github.com/miekg/dns"
  version = "~1.0.15"
