# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/caddyserver/caddy"
  version = "~1.0.1"

[[override]]
  name = "github.com/russross/blackfriday"
  revision = "067529f716f4c3f5e37c8c95ddd59df1007290ae"

[[override]]
  name = "github.com/lucas-clemente/quic-go"
  version = "~0.10.2"

[[override]]
  name = "github.com/bifurcation/mint"
  revision = "824af65410658916142a7600349144e1289f2110"

[[override]]
  name = "github.com/mholt/certmagic"
  revision = "8ae95e4443945598c6b84ff5aa5761089a934b7e"
